# Generated by Django 4.2.4 on 2023-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.IntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('serialno', models.CharField(blank=True, max_length=50, null=True)),
                ('logdate', models.DateField(blank=True, null=True)),
                ('first_logtime', models.TimeField(blank=True, null=True)),
                ('last_logtime', models.TimeField(blank=True, null=True)),
                ('total_time', models.DurationField(null=True)),
            ],
            options={
                'db_table': 'Processed_Data',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idno', models.IntegerField(blank=True, null=True)),
                ('employeeid', models.IntegerField(blank=True, null=True)),
                ('logdate', models.DateField(blank=True, null=True)),
                ('logtime', models.TimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('serialno', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Raw_Data',
            },
        ),
    ]
