# Generated by Django 4.2.4 on 2023-08-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_employeedetails_employeelogs_delete_processeddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogs',
            name='FIRST_LOGTIME',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeelogs',
            name='LAST_LOGTIME',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeelogs',
            name='TOTAL_LOGTIME',
            field=models.DurationField(null=True),
        ),
    ]
