# Generated by Django 4.2.4 on 2023-08-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0003_alter_employeelogs_first_logtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogs',
            name='DIRECTION',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeelogs',
            name='LOGDATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
