# Generated by Django 4.2.4 on 2023-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0005_gislogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogs',
            name='FIRST_LOGTIME',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeelogs',
            name='LAST_LOGTIME',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
